### ISSUE TITLE
Get App Running and Working on Server

### ISSUE THREAD

**Issue by jcworkma** [gios-asu/text-geolocator#45]

**Comment by idmontie** [comment]
:+1:

**Comment by wtneal** [comment]
I've already spent hours trying to get the thing to work, but if fails the tests every time. Part of the problem is that it can't download all of the NLTK dictionaries/support files. If I try to do that manually after the initialization, I get errors. This is either due the fact that the files are located in a different location, or some other issue that I have yet to discover. Since Docker is being used, I am not sure what the issue is because the environments that the app is running in should be identical. I am trying to find out what is different between the VM environments, where the tests run without issue and the server environment where they fail.

For a look at what the errors are here is the gist that I shared with the group last week. Unfortunately there is no help from Google with these errors.
[https://gist.github.com/wtneal/1fd30fd1f0f9b89c9414](https://gist.github.com/wtneal/1fd30fd1f0f9b89c9414)

**Comment by wtneal** [comment]
So the problem has been identified. There is not enough memory to even load all the NLTK support files, hence the EOF errors that it returns when downloading. Even if those are imported manually after the process, the server has trouble processing requests with so little memory. After recreating another VM with 1GB of RAM, the tests all ran, with little trouble.

[https://gist.githubusercontent.com/wtneal/49f646edae8f7bb130f3/raw/b71a3a7f1f1e3ff5d42c330edad0630634d634c4/New%20error%20output](https://gist.githubusercontent.com/wtneal/49f646edae8f7bb130f3/raw/b71a3a7f1f1e3ff5d42c330edad0630634d634c4/New%20error%20output)

**Comment by idmontie** [comment]
Are we talking about the Digital Ocean server?  Did you increase the Swap File like we mentioned last semester? https://www.digitalocean.com/community/tutorials/how-to-configure-virtual-memory-swap-file-on-a-vps

**Comment by wtneal** [comment]
Ok I implemented the swap space. I am pretty sure that it should be persistent since I added an entry into the fstab. If we have issues again let me know an I can look into it.

As of now the server seems to be running the latest version of app just fine. It is passing all of the tests but one, that seems to have an error in the test case.
